[platformio]
default_envs = esp32-s3

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2
    dfrobot/DFRobot_BMI160
    adafruit/Adafruit NeoPixel

; make bring-up test: I2C scan + display + IMU read (src/main.cpp)
[env:esp32-s3]
build_src_filter = +<main.cpp> -<test_orientation.cpp>

; test 2: flips the display 180 based on IMU accel (src/test_orientation.cpp)
[env:esp32-s3-orientation]
build_src_filter = +<test_orientation.cpp> -<main.cpp>



; test 3: flips the display 180, changes LED color based on IMU accel (src/test_orientation_led.cpp)
[env:esp32-s3-orientation]
build_src_filter = +<test_orientation_led.cpp> -<main.cpp>